name: Generate Requirements.txt
on: 
  push:
    branches: [ "main" ]
    
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@main
      - name: Automatic requirements.txt for Python Projects
  # You may pin to the exact commit or the version.
  # uses: ryan-rozario/pipreqs-action@d49032f58167fcc8d6979d6ce4c4fd9cf6ca1592
        uses: ryan-rozario/pipreqs-action@v3.0.0
        with:
          PROJECT_NAME: python-learning-project
          
